### ISSUE TITLE
H61E0 cannot set scenes via Platform API

### ISSUE THREAD

**Issue by jnbp** [wez/govee2mqtt#71] opened 2024-01-15 02:42 UTC
### Govee Device SKU

 H61E0

### Govee2MQTT Version

2024.01.14-3c7b22d4

### Describe the issue

Somehow the effects are not working anymore with my 2 m stripes.
Everything was fine, but the last days I assume some of the updates crashed it.
With homebridge it works well (custom scene selection) So that means the leds are set up properly.
Any chance the master can fix this? :)

### Startup Diagnostics

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
GOVEE_API_KEY=REDACTED
GOVEE_MQTT_HOST=core-mosquitto
GOVEE_EMAIL=REDACTED
GOVEE_PASSWORD=REDACTED
GOVEE_MQTT_PASSWORD=REDACTED
GOVEE_MQTT_USER=addons
GOVEE_MQTT_PORT=1883
++ cd /app
++ exec /app/govee serve
[2024-01-15T03:33:44 INFO  govee::commands::serve] Starting service. version 2024.01.14-3c7b22d4
[2024-01-15T03:33:44 INFO  govee::commands::serve] Querying platform API for device list
[2024-01-15T03:33:44 INFO  govee::commands::serve] Querying undocumented API for device + room list
[2024-01-15T03:33:45 INFO  govee::service::iot] Connected to IoT: CONNACK code 0: Connection Accepted.
[2024-01-15T03:33:45 INFO  govee::service::iot] IoT (re)connected with status CONNACK code 0: Connection Accepted.
[2024-01-15T03:33:45 INFO  govee::commands::serve] Starting LAN discovery
[2024-01-15T03:33:45 INFO  govee::commands::serve] Waiting 10 seconds for LAN API discovery
[2024-01-15T03:33:55 INFO  govee::commands::serve] Devices returned from Govee's APIs
[2024-01-15T03:33:55 INFO  govee::commands::serve] H5054_4160 (XXXXXXXXXXXXXXXXXXX H5054)
[2024-01-15T03:33:55 INFO  govee::commands::serve]   Undoc: room=Some("Studio") supports_iot=false ble_only=true
[2024-01-15T03:33:55 WARN  govee::commands::serve]   Unknown device type. Cannot map to Home Assistant.
[2024-01-15T03:33:55 INFO  govee::commands::serve] 
[2024-01-15T03:33:55 INFO  govee::commands::serve] H5054_3142 (XXXXXXXXXXXXXXXXXXX H5054)
[2024-01-15T03:33:55 INFO  govee::commands::serve]   Undoc: room=Some("Studio") supports_iot=false ble_only=true
[2024-01-15T03:33:55 WARN  govee::commands::serve]   Unknown device type. Cannot map to Home Assistant.
[2024-01-15T03:33:55 INFO  govee::commands::serve] 
[2024-01-15T03:33:55 INFO  govee::commands::serve] Badezimmer Waschbecken (XXXXXXXXXXXXXXXXXXX H61E0)
[2024-01-15T03:33:55 INFO  govee::commands::serve]   LAN API: ip=192.168.178.32
[2024-01-15T03:33:55 INFO  govee::commands::serve]   Platform API: devices.types.light. supports_rgb=true supports_brightness=true
[2024-01-15T03:33:55 INFO  govee::commands::serve]                 color_temp=Some((2000, 9000)) segment_rgb=Some(0..15)
[2024-01-15T03:33:55 INFO  govee::commands::serve]   Undoc: room=Some("Badezimmer") supports_iot=true ble_only=false
[2024-01-15T03:33:55 INFO  govee::commands::serve]   Quirk { sku: "H61E0", icon: "mdi:light-bulb", supports_rgb: true, supports_brightness: true, color_temp_range: Some((2000, 9000)), avoid_platform_api: false, ble_only: false, lan_api_capable: true, device_type: Light, platform_temperature_sensor_units: None, platform_humidity_sensor_units: None, iot_api_supported: true }
[2024-01-15T03:33:55 INFO  govee::commands::serve] 
[2024-01-15T03:33:55 INFO  govee::commands::serve] Küche Arbeitsplatte (XXXXXXXXXXXXXXXXXXX H61E0)
[2024-01-15T03:33:55 INFO  govee::commands::serve]   LAN API: ip=192.168.178.38
[2024-01-15T03:33:55 INFO  govee::commands::serve]   Platform API: devices.types.light. supports_rgb=true supports_brightness=true
[2024-01-15T03:33:55 INFO  govee::commands::serve]                 color_temp=Some((2000, 9000)) segment_rgb=Some(0..15)
[2024-01-15T03:33:55 INFO  govee::commands::serve]   Undoc: room=Some("Küche") supports_iot=true ble_only=false
[2024-01-15T03:33:55 INFO  govee::commands::serve]   Quirk { sku: "H61E0", icon: "mdi:light-bulb", supports_rgb: true, supports_brightness: true, color_temp_range: Some((2000, 9000)), avoid_platform_api: false, ble_only: false, lan_api_capable: true, device_type: Light, platform_temperature_sensor_units: None, platform_humidity_sensor_units: None, iot_api_supported: true }
[2024-01-15T03:33:55 INFO  govee::commands::serve] 
[2024-01-15T03:33:55 INFO  govee::commands::serve] H5054_2AE0 (XXXXXXXXXXXXXXXXXXX H5054)
[2024-01-15T03:33:55 INFO  govee::commands::serve]   Undoc: room=Some("Küche") supports_iot=false ble_only=true
[2024-01-15T03:33:55 WARN  govee::commands::serve]   Unknown device type. Cannot map to Home Assistant.
[2024-01-15T03:33:55 INFO  govee::commands::serve] 
[2024-01-15T03:33:55 INFO  govee::commands::serve] Küche Schränke (XXXXXXXXXXXXXXXXXXX H61E1)
[2024-01-15T03:33:55 INFO  govee::commands::serve]   LAN API: ip=192.168.178.39
[2024-01-15T03:33:55 INFO  govee::commands::serve]   Platform API: devices.types.light. supports_rgb=true supports_brightness=true
[2024-01-15T03:33:55 INFO  govee::commands::serve]                 color_temp=Some((2000, 9000)) segment_rgb=Some(0..15)
[2024-01-15T03:33:55 INFO  govee::commands::serve]   Undoc: room=Some("Küche") supports_iot=true ble_only=false
[2024-01-15T03:33:55 INFO  govee::commands::serve]   Quirk { sku: "H61E1", icon: "mdi:led-strip-variant", supports_rgb: true, supports_brightness: true, color_temp_range: Some((2000, 9000)), avoid_platform_api: false, ble_only: false, lan_api_capable: true, device_type: Light, platform_temperature_sensor_units: None, platform_humidity_sensor_units: None, iot_api_supported: true }
[2024-01-15T03:33:55 INFO  govee::commands::serve] 
[2024-01-15T03:33:55 INFO  govee::service::http] http server addr is 0.0.0.0:8056
[2024-01-15T03:34:03 INFO  govee::service::hass] Wait 3.3s for hass to settle on 66 entity configs
[2024-01-15T03:34:07 INFO  govee::service::hass] MQTT connected with status=CONNACK code 0: Connection Accepted.
[2024-01-15T03:34:16 INFO  govee::service::hass] Command for Küche Arbeitsplatte (XXXXXXXXXXXXXXXXXXX H61E0): {"state":"ON","effect":"Aurora-A"}
[2024-01-15T03:34:16 INFO  govee::service::state] Using Platform API to set Küche Arbeitsplatte (XXXXXXXXXXXXXXXXXXX H61E0) to scene Aurora-A

**Comment by wez** [comment] 2024-01-16 01:38
The `H5054` devices appear to BLE-only devices from the logs; there is no way for govee2mqtt to control them as it does not have any BLE support.  Are you sure that you were able to control them in the past?

Now, the issue summary is talking about H5054, but you just mentioned a 2m strip. Is that a different device?

If you suddenly are unable to use the platform API to talk to your devices, it may indicate a networking problem; your govee devices require access to the public internet in order to work with the platform or IoT APIs.

**Comment by jnbp** [comment] 2024-01-17 01:08
Hi @wez, thanks for you answer!
Sorry, I did not wanted to confuse you with the H5054. This one I could never control ealier.

It is about the 2m and 5m M1 stripe.
Suddently selecting effects just works on the 5m but not on the 2m. On Off or also single colors works on the 2m, but just the effects are not working. I tried to restart and re-configure, hence it did not solve it.
Do you have an idea?

**Comment by wez** [comment] 2024-01-18 05:33
Please update to the latest version and share the logs from around your attempts to set scenes

**Comment by wez** [comment] 2024-01-18 05:34
and please fix the SKU on this issue; I don't know which of the lights in your logs you are referring to when you say 2m. Thanks!

**Comment by jnbp** [comment] 2024-01-18 15:09
Hi @wez,
sure!

I have the latest version installed.

Here the logs. Looking good, no warning when setting the scenes/effects, however the scene does not sets. It is so strange, becuase it worked last weeks on both of my 2m stripes (H61E0). On the 5m (H61E1) it works well.
Normal single color options are working well, just the effects/scenes are an issue.

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
GOVEE_API_KEY=REDACTED
GOVEE_MQTT_HOST=core-mosquitto
GOVEE_TEMPERATURE_SCALE=C
GOVEE_EMAIL=REDACTED
GOVEE_PASSWORD=REDACTED
GOVEE_MQTT_PASSWORD=REDACTED
GOVEE_MQTT_USER=addons
GOVEE_MQTT_PORT=1883
++ cd /app
++ exec /app/govee serve
[2024-01-18T16:03:04 INFO  govee::commands::serve] Starting service. version 2024.01.17-5df26edb
[2024-01-18T16:03:04 INFO  govee::commands::serve] Querying platform API for device list
[2024-01-18T16:03:04 INFO  govee::commands::serve] Querying undocumented API for device + room list
[2024-01-18T16:03:05 INFO  govee::service::iot] Connected to IoT: CONNACK code 0: Connection Accepted.
[2024-01-18T16:03:05 INFO  govee::service::iot] IoT (re)connected with status CONNACK code 0: Connection Accepted.
[2024-01-18T16:03:05 INFO  govee::commands::serve] Starting LAN discovery
[2024-01-18T16:03:05 INFO  govee::commands::serve] Waiting 10 seconds for LAN API discovery
[2024-01-18T16:03:15 INFO  govee::commands::serve] Devices returned from Govee's APIs
[2024-01-18T16:03:15 INFO  govee::commands::serve] Küche Schränke (11:16:CE:35:33:35:07:61 H61E1)
[2024-01-18T16:03:15 INFO  govee::commands::serve]   LAN API: ip=192.168.178.39
[2024-01-18T16:03:15 INFO  govee::commands::serve]   Platform API: devices.types.light. supports_rgb=true supports_brightness=true
[2024-01-18T16:03:15 INFO  govee::commands::serve]                 color_temp=Some((2000, 9000)) segment_rgb=Some(0..15)
[2024-01-18T16:03:15 INFO  govee::commands::serve]   Undoc: room=Some("Küche") supports_iot=true ble_only=false
[2024-01-18T16:03:15 INFO  govee::commands::serve]   Quirk { sku: "H61E1", icon: "mdi:led-strip-variant", supports_rgb: true, supports_brightness: true, color_temp_range: Some((2000, 9000)), avoid_platform_api: false, ble_only: false, lan_api_capable: true, device_type: Light, platform_temperature_sensor_units: None, platform_humidity_sensor_units: None, iot_api_supported: true, show_as_preset_buttons: None }
[2024-01-18T16:03:15 INFO  govee::commands::serve] 
[2024-01-18T16:03:15 INFO  govee::commands::serve] Badezimmer Waschbecken (9E:8C:CC:35:33:35:55:4A H61E0)
[2024-01-18T16:03:15 INFO  govee::commands::serve]   LAN API: ip=192.168.178.32
[2024-01-18T16:03:15 INFO  govee::commands::serve]   Platform API: devices.types.light. supports_rgb=true supports_brightness=true
[2024-01-18T16:03:15 INFO  govee::commands::serve]                 color_temp=Some((2000, 9000)) segment_rgb=Some(0..15)
[2024-01-18T16:03:15 INFO  govee::commands::serve]   Undoc: room=Some("Badezimmer") supports_iot=true ble_only=false
[2024-01-18T16:03:15 INFO  govee::commands::serve]   Quirk { sku: "H61E0", icon: "mdi:light-bulb", supports_rgb: true, supports_brightness: true, color_temp_range: Some((2000, 9000)), avoid_platform_api: false, ble_only: false, lan_api_capable: true, device_type: Light, platform_temperature_sensor_units: None, platform_humidity_sensor_units: None, iot_api_supported: true, show_as_preset_buttons: None }
[2024-01-18T16:03:15 INFO  govee::commands::serve] 
[2024-01-18T16:03:15 INFO  govee::commands::serve] H5054_2AE0 (BEFF4D928F1B002AE0 H5054)
[2024-01-18T16:03:15 INFO  govee::commands::serve]   Undoc: room=Some("Küche") supports_iot=false ble_only=true
[2024-01-18T16:03:15 WARN  govee::commands::serve]   Unknown device type. Cannot map to Home Assistant.
[2024-01-18T16:03:15 INFO  govee::commands::serve] 
[2024-01-18T16:03:15 INFO  govee::commands::serve] H5054_3142 (BEFF4D928F1B003142 H5054)
[2024-01-18T16:03:15 INFO  govee::commands::serve]   Undoc: room=Some("Studio") supports_iot=false ble_only=true
[2024-01-18T16:03:15 WARN  govee::commands::serve]   Unknown device type. Cannot map to Home Assistant.
[2024-01-18T16:03:15 INFO  govee::commands::serve] 
[2024-01-18T16:03:15 INFO  govee::commands::serve] H5054_4160 (BEFF4D928F1B004160 H5054)
[2024-01-18T16:03:15 INFO  govee::commands::serve]   Undoc: room=Some("Studio") supports_iot=false ble_only=true
[2024-01-18T16:03:15 WARN  govee::commands::serve]   Unknown device type. Cannot map to Home Assistant.
[2024-01-18T16:03:15 INFO  govee::commands::serve] 
[2024-01-18T16:03:15 INFO  govee::commands::serve] Küche Arbeitsplatte (6B:3A:C4:32:32:33:19:73 H61E0)
[2024-01-18T16:03:15 INFO  govee::commands::serve]   LAN API: ip=192.168.178.38
[2024-01-18T16:03:15 INFO  govee::commands::serve]   Platform API: devices.types.light. supports_rgb=true supports_brightness=true
[2024-01-18T16:03:15 INFO  govee::commands::serve]                 color_temp=Some((2000, 9000)) segment_rgb=Some(0..15)
[2024-01-18T16:03:15 INFO  govee::commands::serve]   Undoc: room=Some("Küche") supports_iot=true ble_only=false
[2024-01-18T16:03:15 INFO  govee::commands::serve]   Quirk { sku: "H61E0", icon: "mdi:light-bulb", supports_rgb: true, supports_brightness: true, color_temp_range: Some((2000, 9000)), avoid_platform_api: false, ble_only: false, lan_api_capable: true, device_type: Light, platform_temperature_sensor_units: None, platform_humidity_sensor_units: None, iot_api_supported: true, show_as_preset_buttons: None }
[2024-01-18T16:03:15 INFO  govee::commands::serve] 
[2024-01-18T16:03:16 INFO  govee::service::http] http server addr is 0.0.0.0:8056
[2024-01-18T16:03:23 INFO  govee::service::hass] Wait 3.3s for hass to settle on 66 entity configs
[2024-01-18T16:03:26 INFO  govee::service::hass] MQTT connected with status=CONNACK code 0: Connection Accepted.
[2024-01-18T16:03:38 INFO  govee::service::hass] Command for Küche Arbeitsplatte (6B:3A:C4:32:32:33:19:73 H61E0): {"state":"ON","effect":"Afternoon"}
[2024-01-18T16:03:38 INFO  govee::service::state] Using Platform API to set Küche Arbeitsplatte (6B:3A:C4:32:32:33:19:73 H61E0) to scene Afternoon
[2024-01-18T16:03:39 INFO  govee::platform_api] control_device result: ControlDeviceResponse { request_id: "uuid", code: 200, message: "success", capability: ControlDeviceResponseCapability { kind: DynamicScene, instance: "lightScene", value: Object {"id": Number(176), "paramId": Number(158)}, state: Object {"status": String("success")} } }`

**Comment by wez** [comment] 2024-01-18 15:12
Thanks; those logs show that Govee's API said that the scene change was successful. If it is not actually working then there is either a networking issue with the device that is preventing it from talking to Govee's cloud, or there is a problem on Govee's side that is preventing this from working, and you'll need to raise an issue with their support team about it.

**Comment by jnbp** [comment] 2024-01-18 15:37
Hi @wez exactly, that is the strange thing. However they are not changing the scenes. And with they I mean 2 H61E0s which are doing the same behaviour.
Network issues can not be the problem, since all single color functions are working (on/off, colors, temperature, single colors).
Everything works perfectly excepts the effects.
With the homebridge intergration it works well (also the effects).
(Yes, I am not runnning both at parallel :) )

**Comment by wez** [comment] 2024-01-18 15:50
The homebridge integration uses undocumented APIs. Those *could* be applied here with a bit of effort and verification. At the moment the cause of problems with this issue is that the platform API doesn't do what it says it will do.

**Comment by jnbp** [comment] 2024-01-18 15:52
Ok, understood. And you are using the recently released Platform API.
However, that would mean, that everyone with a H61E0 is facing the issue to not set effects?

**Comment by wez** [comment] 2024-01-18 15:52
I've filed https://github.com/wez/govee2mqtt/issues/83 to track supporting IoT scene control

**Comment by wez** [comment] 2024-01-18 15:55
> Ok, understood. And you are using the recently released Platform API. However, that would mean, that everyone with a H61E0 is facing the issue to not set effects?

Correct. There are a log of bugs in the Platform API which you can see if you skim https://developer.govee.com/discuss

Reverse engineering the IoT API is a lot of effort; while I can leverage the work done on the homebridge govee integration, it isn't guaranteed to work for every device or even completely, and most importantly: it is time consuming and all of my devices behave correctly when the platform API is used to set a scene, so I don't have a lot of personal motivation to resolve this Govee issue.

I'd recommend raising it with Govee!

**Comment by wez** [comment] 2024-01-18 15:57
As an alternative option, see: https://github.com/wez/govee2mqtt/blob/main/docs/FAQ.md#how-do-i-enable-video-effects-for-a-light

**Comment by jnbp** [comment] 2024-01-18 15:57
Ok, understood, many thanks @wez!
Meaning you don't have a H61E0 haha
Let me know in case I can provide you anything! :)

**Comment by jnbp** [comment] 2024-01-22 17:29
Hi @wez, many thanks! It works now after a couple restart of the devices. Very strange however, because only the effects were not working, everything else was fine. Also via internet.

Will post in case I found out more. Many thanks for your great work!

**Comment by wez** [comment] 2024-01-22 18:07
Sounds like maybe Govee shipped a fix on their end.  Let's close this: you can always open a new issue in the future if needed.

**Closed by wez** 2024-01-22 18:07 UTC
Labels: responsible:govee
