### ISSUE TITLE
H6159 That does not support LAN Control - Not supporting to Cloud Control?

### ISSUE THREAD

**Issue by coolspot18** [wez/govee2mqtt#180] opened 2024-04-28 17:45 UTC
### Govee Device SKU

H6159

### Govee2MQTT Version

2024.01.24-ea3cd43

### Describe the issue

I have an older H6159 that does not support LAN control and only cloud control. Govee2MQTT correctly identifies LAN control is not enabled and tries to issue an IoT platform command but the lights do not respond to button presses.

Does this add-on support the legacy Cloud API?

### Startup Diagnostics

[2024-04-28T13:29:32 INFO  govee::commands::serve] 
[2024-04-28T13:29:32 INFO  govee::commands::serve] Media Shelf Lights (1C:0A:A4:C1:38:36:3C:E0 H6159)
[2024-04-28T13:29:32 INFO  govee::commands::serve]   Platform API: devices.types.light. supports_rgb=true supports_brightness=true
[2024-04-28T13:29:32 INFO  govee::commands::serve]                 color_temp=Some((2000, 9000)) segment_rgb=None
[2024-04-28T13:29:32 INFO  govee::commands::serve]   Undoc: room=Some("Rec Room") supports_iot=true ble_only=false
[2024-04-28T13:29:32 INFO  govee::commands::serve]   Quirk { sku: "H6159", icon: "mdi:led-strip-variant", supports_rgb: true, supports_brightness: true, color_temp_range: Some((2000, 9000)), avoid_platform_api: false, ble_only: false, lan_api_capable: true, device_type: Light, platform_temperature_sensor_units: None, platform_humidity_sensor_units: None, iot_api_supported: true, show_as_preset_buttons: None }
[2024-04-28T13:29:32 WARN  govee::commands::serve]   This device should be available via the LAN API, but didn't respond to probing yet. Possible causes:
[2024-04-28T13:29:32 WARN  govee::commands::serve]   1) LAN API needs to be enabled in the Govee Home App.
[2024-04-28T13:29:32 WARN  govee::commands::serve]   2) The device is offline.
[2024-04-28T13:29:32 WARN  govee::commands::serve]   3) A network configuration issue is preventing communication.
[2024-04-28T13:29:32 INFO  govee::commands::serve] 

### Additional Logs

[2024-04-28T13:42:27 INFO  govee::service::state] Using IoT API to set Media Shelf Lights (1C:0A:A4:C1:38:36:3C:E0 H6159) power state
[2024-04-28T13:42:36 INFO  govee::service::hass] Command for Media Shelf Lights (1C:0A:A4:C1:38:36:3C:E0 H6159): {"state":"OFF"}
[2024-04-28T13:42:36 INFO  govee::service::state] Using IoT API to set Media Shelf Lights (1C:0A:A4:C1:38:36:3C:E0 H6159) light power state
[2024-04-28T13:42:40 INFO  govee::service::hass] powerSwitch for 1C0AA4C138363CE0: OFF
[2024-04-28T13:42:40 INFO  govee::service::state] Using IoT API to set Media Shelf Lights (1C:0A:A4:C1:38:36:3C:E0 H6159) power state
[2024-04-28T13:42:54 INFO  govee::service::hass] Command for Media Shelf Lights (1C:0A:A4:C1:38:36:3C:E0 H6159): {"state":"OFF"}
[2024-04-28T13:42:54 INFO  govee::service::state] Using IoT API to set Media Shelf Lights (1C:0A:A4:C1:38:36:3C:E0 H6159) light power state

**Comment by wez** [comment] 2024-04-29 16:15
Duplicate of https://github.com/wez/govee2mqtt/issues/125

**Closed by wez** 2024-04-29 16:15 UTC
