### ISSUE TITLE
Light strip doesn't work in google home but works in HA

### ISSUE THREAD

**Issue by jonathanrobichaud4** [wez/govee2mqtt#70] opened 2024-01-14 22:01 UTC
### Govee Device SKU

H619A

### Govee2MQTT Version

2024.01.13-b7277f05

### Describe the issue

My lightstrip works just fine in Home assistant but Google Home says "Not Responding". However, my Govee glide (H6062) works perfectly on google home and HA. I have no idea what the issue could be. It worked fine with the govee Lan integration before.

### Startup Diagnostics

[2024-01-14T17:33:34 INFO  govee::commands::serve] Starting service. version 2024.01.13-b7277f05
[2024-01-14T17:33:34 INFO  govee::commands::serve] Querying platform API for device list
[2024-01-14T17:33:34 INFO  govee::commands::serve] Starting LAN discovery
[2024-01-14T17:33:34 INFO  govee::commands::serve] Waiting 10 seconds for LAN API discovery
[2024-01-14T17:33:44 INFO  govee::commands::serve] Devices returned from Govee's APIs
[2024-01-14T17:33:44 INFO  govee::commands::serve] Bedroom (A6:D4:D4:AD:FC:A4:BD:DB H619A)
[2024-01-14T17:33:44 INFO  govee::commands::serve]   LAN API: ip=10.5.0.42
[2024-01-14T17:33:44 INFO  govee::commands::serve]   Platform API: devices.types.light. supports_rgb=true supports_brightness=true
[2024-01-14T17:33:44 INFO  govee::commands::serve]                 color_temp=Some((2000, 9000)) segment_rgb=Some(0..15)
[2024-01-14T17:33:44 INFO  govee::commands::serve]   Quirk { sku: "H619A", icon: "mdi:led-strip-variant", supports_rgb: true, supports_brightness: true, color_temp_range: Some((2000, 9000)), avoid_platform_api: false, ble_only: false, lan_api_capable: true, device_type: Light, platform_temperature_sensor_units: None, platform_humidity_sensor_units: None, iot_api_supported: true }
[2024-01-14T17:33:44 INFO  govee::commands::serve] 
[2024-01-14T17:33:44 INFO  govee::commands::serve] Bedroom glide (65:39:D2:36:39:34:32:68 H6062)
[2024-01-14T17:33:44 INFO  govee::commands::serve]   LAN API: ip=10.5.0.41
[2024-01-14T17:33:44 INFO  govee::commands::serve]   Platform API: devices.types.light. supports_rgb=true supports_brightness=true
[2024-01-14T17:33:44 INFO  govee::commands::serve]                 color_temp=Some((2000, 9000)) segment_rgb=Some(0..28)
[2024-01-14T17:33:44 INFO  govee::commands::serve]   Quirk { sku: "H6062", icon: "mdi:led-strip-variant", supports_rgb: true, supports_brightness: true, color_temp_range: Some((2000, 9000)), avoid_platform_api: false, ble_only: false, lan_api_capable: true, device_type: Light, platform_temperature_sensor_units: None, platform_humidity_sensor_units: None, iot_api_supported: true }
[2024-01-14T17:33:44 INFO  govee::commands::serve] 
[2024-01-14T17:33:44 INFO  govee::service::http] http server addr is 0.0.0.0:8056
[2024-01-14T17:33:49 INFO  govee::service::hass] Wait 2.75s for hass to settle on 55 entity configs
[2024-01-14T17:33:52 INFO  govee::service::hass] MQTT connected with status=CONNACK code 0: Connection Accepted.

**Comment by wez** [comment] 2024-01-14 23:43
I'm not sure how Google Home fits in to this; is it talking to Govee2MQTT or Home Assistant?

**Comment by jonathanrobichaud4** [comment] 2024-01-15 00:24
That’s what I’m saying. I’m really confused by it and I couldn’t find anything in the logs that looked like an error. The light works within home assistant just fine so it’s super weird.

**Comment by wez** [comment] 2024-01-15 00:38
if you have not configured google home to talk to your home assistant instance, then this sounds like it is not an issue with govee2mqtt.  If google is trying to control your device via govee2mqtt then you'll need to capture some logs from it attempting that control so that we can see what is failing.  If nothing is failing in the govee2mqtt logs, then it is unlikely to be an issue in this project.

**Comment by jonathanrobichaud4** [comment] 2024-01-15 00:48
Google home is connected to home assistant and all of the devices that are exposed are working.  This includes my Govee glide which is also exposed through G2M and is working through Google home. I’m not at home right now so I’ll do some debug logging later and attach them here if anything seems wrong

**Comment by jonathanrobichaud4** [comment] 2024-01-16 02:06
Ok yeah I don't think this is an issue with G2M I've looked through the logs and couldn't see anything. I think it may be an issue with the google assistant integration. If I find anything that I think has to do with G2M I'll reopen the issue but for now it can be marked as whatever is most appropriate

**Comment by jonathanrobichaud4** [comment] 2024-01-16 02:20
I just did an experiment and I am going to have to dig deeper but something in the state reporting seems possibly broken? Basically I had a light group that I made in HA and it has the light strip in it. I added that group to google assistant and it was also giving me "No Response". Once I remove the light strip and refresh the devices the light group begins to work just fine. I have debug logs enabled for google assistant and it looks to be showing state reporting just fine. I removed my govee credentials and now it is available in google home. Maybe it has to do with the effect list?

**Comment by wez** [comment] 2024-01-16 04:49
I don't use google home and there's not enough detail here for me to help you figure this out. It sounds like this may be an issue with google and HA rather than an issue with Govee2MQTT.  I'm going to close this: it's not productive for me to keep coming back to this issue.

**Closed by wez** 2024-01-16 04:49 UTC

**Comment by Darcody** [comment] 2024-05-29 20:40
I have the same issue with the same lightstrip. In HA the lightstrip enitity works really good. Far better that with the _govee lan hass_ plugin. But in the Google Home app it always states as offline or only shortly online after toggling its state in HA.
With the _govee lan hass_ plugin the lightstrip worked with Google Home.

I have also an H6159 lightstrip that works as intended with Google Home.

@jonathanrobichaud4 did you ever found a solution for this issue?

I tried to compare the MQTT messages between the two lightstrips and I cannot find anything obvious, that would explain, why the H619A behaves like that. @wez is there someting else I could check on Govee2MQTTs side?

**Comment by jonathanrobichaud4** [comment] 2024-06-01 18:45
I never actually figured it out and ended up converting both of my govee lights to WLED just to make it easier for me. I know this isn't the answer you were looking for unfortunately. I do have a theory that it's the number of effects that govee2mqtt picks up for that strip specifically. It's really weird but when I edit the state in home assistant's developer tools and remove some effects it allowed me to control it and set the effect I left in the state editor from Google assistant.

**Comment by Skwerl23** [comment] 2024-08-12 02:43
This is still an issue. and should not have been closed

I have a new govee led strip, and it won't show as online inside google home. but works in google assistant. 
Maybe there is an effect size limit for google home?
