### ISSUE TITLE
Request for change-logs with updates

### ISSUE THREAD

**Issue by J-D-Torres** [wez/govee2mqtt#52] opened 2024-01-11 17:29 UTC
### Govee Device SKU

N/A

### Govee2MQTT Version

2024.01.11-6a00caa3

### Describe the issue

I've noticed that the recent updates to the codebase do not include a changelog. 

The absence of a changelog makes it challenging to track the progression of the project, understand new features, and identify bug fixes. This can lead to confusion and a decrease in the project's transparency and maintainability.

I would like to kindly request that a changelog be maintained for the `govee2mqtt` project with what is updated so as we can better understand the work being done. 

Including a changelog would greatly benefit the your user base by:

- Providing a clear history of the project's development.
- Making it easier for users to see what has changed without having to dig through commit messages.
- Helping developers to avoid potential conflicts with their own work based on recent changes (breaking changes).
- Enhancing the overall communication within the project's community.

### Startup Diagnostics

n/a

### Anything else?

![Screenshot 2024-01-11 122346](https://github.com/wez/govee2mqtt/assets/108241392/719f7305-977f-4135-9627-4a98e17ad00c)

**Comment by wez** [comment] 2024-01-11 23:03
Please don't lecture me about why a changelog is nice for users.

To be frank: I don't have time for it. I can either spend time working on responding to issues, improving things, or I can spend time writing up a duplicate of my commit messages.

I am already dramatically outnumbered by my users, who are getting a LOT from me where I get very little to nothing in return.

**Comment by KommanderKeen1** [comment] 2024-01-11 23:07
Ya, it's not hard to read the commits. Perhaps someone can volunteer to maintain a change log? I'd help if I knew where to start. I'm only staying to get my feet wet. Thank-you for all your helpful work and time.

**Comment by KyleStilkey** [comment] 2024-01-12 01:45
Amy chance you could just add a changlog if it's something small just say a simple bug fixes, and if it's some significant that's where you can put some details that way if say you add new features or devices we can try and properly test and or know what's going on.

Trust me a lot of us appreciate your hard work it's not easy, but I'd also like to add it would be wonderful if you had a way listed here for users to donate to you. I'd contribute to your work but I don't see any donation links here.

Thanks again for all you're doing and now that I know this project exists thanks to your last LAN update I'll see if I can help in someway. I'm not very good with Github but I'll do what I can do to help contribute in my free time.

**Comment by J-D-Torres** [comment] 2024-01-12 02:08
Sorry just trying to ask in a polite way. No disrespect intended.

**Comment by wez** [comment] 2024-01-12 03:48
> but I'd also like to add it would be wonderful if you had a way listed here for users to donate to you. I'd contribute to your work but I don't see any donation links here.

I appreciate that. I suppose it's hard to see when we're trained to tune out side bars, but please look at the sidebar of https://github.com/wez/govee2mqtt for multiple options:

![image](https://github.com/wez/govee2mqtt/assets/117777/b8b6845f-771f-4352-9c8c-84a15e78ca41)

I'm genuinely interested to hear where you think it would be good for me to add additional links to that information!

**Closed** 2024-01-12 15:02 UTC

**Comment by KyleStilkey** [comment] 2024-01-16 18:14
> > but I'd also like to add it would be wonderful if you had a way listed here for users to donate to you. I'd contribute to your work but I don't see any donation links here.
> 
> I appreciate that. I suppose it's hard to see when we're trained to tune out side bars, but please look at the sidebar of https://github.com/wez/govee2mqtt for multiple options:
> 
> ![image](https://private-user-images.githubusercontent.com/117777/296121013-b8b6845f-771f-4352-9c8c-84a15e78ca41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MjkwNTgsIm5iZiI6MTcwNTQyODc1OCwicGF0aCI6Ii8xMTc3NzcvMjk2MTIxMDEzLWI4YjY4NDVmLTc3MWYtNDM1Mi05YzhjLTg0YTE1ZTc4Y2E0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQxODEyMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjQ4NjNmMzcwZjllMzdmYjMzY2VmYjI0M2ZjNTg0MWZlNWViMmI0OThiNzAxNzNhZGY0MTc5MDBjZGRjY2U5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Op51daxvsq9LFKdg9uyA-Yf7noR3oWCnXD1oCDLK4Bo)
> 
> I'm genuinely interested to hear where you think it would be good for me to add additional links to that information!

I'd say add it right in the Readme, when on mobile I really miss the sidebar info/details so I just never noticed it at all but as soon as I got onto desktop I saw it there and went oh. Thanks again and appreciate your hard work. In just the past week I've seen you fixing so much I'm astonished. Thanks again!
