### ISSUE TITLE
Govee account login disabled after a few Bridge restarts

### ISSUE THREAD

**Issue by terriblefox** [wez/govee2mqtt#16] opened 2024-01-06 22:11 UTC
I restarted the bride  about 10 times, was testing renaming the DIY scenes. 

i think it is becourse of the bridge restarts.

Got mail from Govee:

Dear customer,
--
 
The system detects that your account is logged in too many times in a row. To ensure the account safety, it will be restricted from being logging in again for 24 hours. If you have any question, please contact support@govee.com.
 
Govee Home!

Dear customer,
 
The system detects that your account is logged in too many times in a row. To ensure the account safety, it will be restricted from being logging in again for 24 hours. If you have any question, please contact [support@govee.com](mailto:support@govee.com).
 
Govee Home!

just to let you know

**Comment by wez** [comment] 2024-01-06 22:15
How many times did it restart?

**Comment by terriblefox** [comment] 2024-01-06 22:17
im not shure didnt count, perhaps 10 times...

**Comment by wez** [comment] 2024-01-06 22:17
And was it quickly in a row with valid credentials, or was it failing to login? Can you share the logs?

**Comment by terriblefox** [comment] 2024-01-06 22:23
changed some stuff in the govee app and restarted. Before it was runnig fine.

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
GOVEE_API_KEY=REDACTED
GOVEE_MQTT_HOST=core-mosquitto
GOVEE_EMAIL=REDACTED
GOVEE_PASSWORD=REDACTED
GOVEE_MQTT_PASSWORD=REDACTED
GOVEE_MQTT_USER=addons
GOVEE_LAN_NO_MULTICAST=false
GOVEE_MQTT_PORT=1883
++ cd /app
++ exec /app/govee serve
[2024-01-06T23:22:56 INFO  govee::commands::serve] Starting service. version 2024.01.06-0da21047
[2024-01-06T23:22:56 INFO  govee::commands::serve] Querying platform API for device list
[2024-01-06T23:22:56 INFO  govee::commands::serve] Querying undocumented API for device + room list
Error: request https://app2.govee.com/account/rest/account/v1/login status 200: OK

Caused by:
    0: parsing https://app2.govee.com/account/rest/account/v1/login response
    1: Failed with status 400 Bad Request Bad Request: Request to https://app2.govee.com/account/rest/account/v1/login failed with code 400 Bad Request Your account is abnormal, please contact customer service.. Full response: {"status":400,"message":"Your account is abnormal, please contact customer service."}

Stack backtrace:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/backtrace.rs:331:13
   3: anyhow::context::<impl anyhow::Context<T,E> for core::result::Result<T,E>>::with_context
   4: govee::undoc_api::GoveeUndocumentedApi::login_account_impl::{{closure}}
   5: govee::commands::serve::ServeCommand::run::{{closure}}
   6: govee::Args::run::{{closure}}
   7: tokio::runtime::park::CachedParkThread::block_on
   8: tokio::runtime::runtime::Runtime::block_on
   9: govee::main
  10: std::sys_common::backtrace::__rust_begin_short_backtrace
  11: std::rt::lang_start::{{closure}}
  12: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:284:13
  13: std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  14: std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  15: std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  16: std::rt::lang_start_internal::{{closure}}
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:48
  17: std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  18: std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  19: std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  20: std::rt::lang_start_internal
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:20
  21: std::rt::lang_start
  22: main
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by wez** [comment] 2024-01-06 22:34
I suspect that those logs are the effect rather than the cause.

I'm sorry that this happened; I had caching around the login credentials, but removed it earlier today because it looked like another user was having problems with the cached value (although really: I think they had accidentally edited and broken their credentials).

I've reinstated the caching and made the negative cache duration longer, so that hopefully no one else hits this same issue.

**Comment by terriblefox** [comment] 2024-01-06 22:35
thanks for the support, will report in 20 hours hows it going 😊 thx

**Comment by terriblefox** [comment] 2024-01-07 21:08
Feedback: as my account API got reactivated all seems running fine now.

**Comment by wez** [comment] 2024-01-07 22:15
Good to hear! Let's close this out!

**Closed by wez** 2024-01-07 22:15 UTC
